/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeSettingsIndexRouteImport } from './routes/home/settings/index'
import { Route as AuthResetPassIndexRouteImport } from './routes/auth/reset-pass/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSettingsIndexRoute = HomeSettingsIndexRouteImport.update({
  id: '/home/settings/',
  path: '/home/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPassIndexRoute = AuthResetPassIndexRouteImport.update({
  id: '/auth/reset-pass/',
  path: '/auth/reset-pass/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/reset-pass': typeof AuthResetPassIndexRoute
  '/home/settings': typeof HomeSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/reset-pass': typeof AuthResetPassIndexRoute
  '/home/settings': typeof HomeSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/home/': typeof HomeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/auth/reset-pass/': typeof AuthResetPassIndexRoute
  '/home/settings/': typeof HomeSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/api/auth/$'
    | '/auth/reset-pass'
    | '/home/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/home'
    | '/api/auth/$'
    | '/auth/reset-pass'
    | '/home/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/home/'
    | '/api/auth/$'
    | '/auth/reset-pass/'
    | '/home/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  HomeIndexRoute: typeof HomeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AuthResetPassIndexRoute: typeof AuthResetPassIndexRoute
  HomeSettingsIndexRoute: typeof HomeSettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/settings/': {
      id: '/home/settings/'
      path: '/home/settings'
      fullPath: '/home/settings'
      preLoaderRoute: typeof HomeSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-pass/': {
      id: '/auth/reset-pass/'
      path: '/auth/reset-pass'
      fullPath: '/auth/reset-pass'
      preLoaderRoute: typeof AuthResetPassIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  HomeIndexRoute: HomeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AuthResetPassIndexRoute: AuthResetPassIndexRoute,
  HomeSettingsIndexRoute: HomeSettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
